### ISSUE TITLE
Parse failed when missing one opt

### ISSUE THREAD

**Issue by BrentHuang** [martinh/libconfuse#14] opened 2014-11-10 10:07 UTC
In my conf file, there is an opt named "repeat", such as:
repeat = 1
target = "Tom"

But in my c++ code, my cfg_opt_t is:
    char optName[] = "target";
    char defValue[] = "world";

```
cfg_opt_t opts[] = {
    CFG_STR(optName, defValue, CFGF_NONE),
    CFG_END()
};
```

libconfuse return failed when calling the function "cfg_parse".

I think it should return ok because I only want to use one of so many opts in my conf file. Why can't I?

**Comment by troglobit** [comment] 2015-10-28 01:23
Looks like a duplicate of #19, right?

**Comment by pkd7742** [comment] 2016-08-18 11:17
set your default something like this..

    opts[0].name = "target";
    opts[0].type = CFGT_STR;
    opts[0].def.string = "world";

set opt size one more than your required to accomodate for CFG_END... 
then parse your config file like this...

    cfg = cfg_init(opts, CFGF_NONE);
    cfg_parse(cfg, pchConfigFile);
    char str[30];
    strcpy(str, cfg_getstr(cfg, "target"));
    std::cout << str << std::endl;

this should work....

**Comment by troglobit** [comment] 2017-05-14 18:11
With PR #91 I'm assuming this is fixed, simply set the `CFGF_IGNORE_UNKNOWN` flag to `cfg_parse()`.

**Closed by troglobit** 2017-05-14 18:11 UTC
