### ISSUE TITLE
Bug with closing braces in CFG_INT_LIST

### ISSUE THREAD

**Issue by ivzaen** [martinh/libconfuse#108] opened 2018-07-02 10:43 UTC
Hello.
I'm using default value for integer list
CFG_INT_LIST("freqFCLK0123", "{50,200,0,0}", CFGF_NONE),
I get an error "Missed one or more closing braces" during default value parsing.
Adding two braces }} in the end helps.
changing level from 1 to 0 in confuse.c:
ret = cfg_parse_internal(cfg, 0, xstate, &cfg->opts[i]);
also helps.
Is the problem with level?

**Comment by troglobit** [comment] 2018-07-02 15:03
This seems to be a regression introduced by @furmur in #106 maybe he can comment on this?

**Comment by troglobit** [comment] 2018-08-19 07:43
Fixed in revert commit 397b713.

**Closed** 2018-08-19 07:43 UTC
